# Generated by Django 3.1.2 on 2020-11-03 23:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.TextField(max_length=1000)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(max_length=1000)),
                ('url', models.URLField(default='', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Genre')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
