# Generated by Django 3.1.2 on 2020-11-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={},
        ),
        migrations.RemoveField(
            model_name='genre',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='juego',
            name='Genre',
        ),
        migrations.AddField(
            model_name='juego',
            name='genre',
            field=models.ManyToManyField(to='catalog.Genre'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
